# Generated by Django 3.0.4 on 2020-04-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200404_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
